// 毎朝9時のタスクがこのファイルを丸ごと書き換えます。
// index.html はこの window.OPENCALLS を読んでカードを描画します。
// 掲載基準：本日時点で公式ページ（応募ページ/募集要項）または信頼できる一次的告知で「受付中（受付期間が開始済み）」＋締切を確認できたものだけ。
window.OPENCALLS = {
  date: "2026年6月7日（日）",
  updated: "2026-06-07",
  intro: "本日（2026/6/7）時点で応募ページ・募集要項まで確認し、受付中＋締切を確認できたものを掲載。受付開始前は『まもなく受付開始』に分離。林稔里をジャンル横断の現代アーティストとして選定。提出済み（GRID NEXT / FF Seoul / NCA / SUBTEXT / YAU / MIDTOWN / SUPERGAU / Saatchi）は除外。",
  sections: [
    {
      label: "A. 国内｜芸術祭・賞・助成・レジデンス（受付中）",
      items: [
        { id: "nakanojo-biennale-2027", title: "中之条ビエンナーレ2027", org: "中之条ビエンナーレ実行委員会｜国内・国際芸術祭", deadline: "2026/07/12", cv: "high", cvText: "高。実空間で発表でき、実物の展示経験と展示風景写真を作れる。採択も現実的。", tags: ["メディア不問", "実物展示", "滞在制作"], what: "群馬県中之条町で隔年開催の国際現代芸術祭。会期2027/9/18〜10/24。山村地域のAIRで滞在制作し成果を発表。多分野を公募。", why: "写真を金属・反射・透明面・公共空間へ展開するインスタ案を、初めて実物として設置できる機会。ジャンル横断の実践を空間でそのまま見せられる。", fee: "Web応募は2026/7/12 23:59まで、郵送は当日消印有効。", url: "https://nakanojo-biennale.com/2027-open-call" },
        { id: "idemitsu-art-award-2026", title: "Idemitsu Art Award 2026（出光アートアワード）", org: "出光興産｜国内・公募賞", deadline: "2026/07/31", cv: "high", cvText: "高。国内の若手登竜門。入選でもギャラリー営業で説明しやすい。", tags: ["1986/4/1以降生まれ", "平面のみ"], what: "旧シェル美術賞。平面作品（絵画・写真・布・刺繍・レリーフ等、ワイヤー吊り展示可）対象。立体・映像・共同制作は不可。グランプリ300万円、入選40〜50点。", why: "《片染め》や転写・mixed mediaの平面で出せる。写真に限らず支持体や素材の扱いを含めて『平面の現代美術』として見せる。", fee: "エントリーは6/1〜7/31（オンライン）、搬入8/20〜23。応募料は25歳以下は無料〜¥11,000。", url: "https://www.idemitsu.com/jp/fun/art/method.html" },
        { id: "kumagai-grant-2026", title: "熊谷正寿文化財団 現代アート作家助成", org: "熊谷正寿文化財団｜国内・制作助成", deadline: "2026/06/30", cv: "mid", cvText: "中。最大100万円の制作助成。受給は実制作の後押しになり、助成歴はCVにも効く。", tags: ["35歳以下", "制作経験3年以上", "原材料費が主対象"], what: "現代アートの制作を支援する助成。助成額は100万円まで。主に作品の原材料費が対象（会場費・生活費は除外）。活動期間は2026/9/1〜2027/8/31。", why: "金属・反射・透明面・立体の実制作の資金になる。応募資格は『募集年度4/1時点で35歳以下・現代アート制作経験3年以上』。", fee: "募集は2026/5/1〜6/30（必着）。", url: "https://kumagai.art/subsidies/" },
        { id: "l-air-2026-himeji", title: "L-AIR 2026（姫路・兵庫）", org: "一般社団法人 L-A・I・R｜国内・レジデンス", deadline: "随時受付中", cv: "mid", cvText: "中〜高。地元・兵庫で渡航負担なし。皮革＝支持体・労働・身体と接続でき作風適合。", tags: ["兵庫・地元", "随時受付", "分野横断"], what: "姫路市高木（皮革産地）のレジデンス。皮革を素材に新しい表現を探究する、分野を超えたアーティストが対象。1.5〜3か月の住み込み制作で随時受付。", why: "写真プリント・手彩色・擦過・皮革支持体・立体を組み合わせ、都市・労働・身体・素材を横断的に扱える。", fee: "応募はサイトのAPPLY FORMから。", url: "https://l-air.or.jp/" },
        { id: "holbein-scholarship-38", title: "ホルベイン・スカラシップ奨学生", org: "ホルベイン｜国内・制作支援（画材提供）", deadline: "2026/07/31", cv: "low", cvText: "低。展示歴ではなく画材支援。CV価値は小さいが制作の実利が大きい。", tags: ["18〜45歳", "国内在住", "画材支援"], what: "色材を使用した制作を行う18〜45歳・日本国内在住者対象。最大7名に総額30万円相当の絵具・筆・キャンバス等を3回に分けて提供。奨学期間2026/12〜2027/11。", why: "《片染め》・オイルスティック作品の画材コストを実質的に下げられる。応募料は無料。", fee: "締切は2026/7/31 12:00。応募無料。", url: "https://www.holbein.co.jp/scholarship.html" }
      ]
    },
    {
      label: "B. 海外｜国際賞・公募（受付中）",
      items: [
        { id: "future-generation-art-prize-2027", title: "Future Generation Art Prize 2027", org: "PinchukArtCentre（キーウ）｜国際・現代美術賞", deadline: "2026/06/28", cv: "high", cvText: "非常に高。応募・ロングリストだけでも国際的射程を示せる。", tags: ["応募無料", "35歳以下", "メディア不問"], what: "35歳以下・メディア不問の国際現代美術賞。主賞US$100,000。入選者展をPinchukArtCentreで開催（2027春）。", why: "ジャンル横断の国際的現代アーティストという目標に直結。平面・金属・インスタ案の強度を併せて出す。", fee: "応募期間は2026/5/11〜6/28。応募無料。", url: "https://futuregenerationartprize.org/en/" },
        { id: "aesthetica-art-prize-2027", title: "Aesthetica Art Prize", org: "Aesthetica Magazine（英国・York）｜国際・公募賞", deadline: "2026/10/11", cv: "high", cvText: "高。英国の主要公的ギャラリーでのグループ展＋£10,000＋誌面掲載。全分野・全レベル対象。", tags: ["メディア不問", "全レベル可", "応募料 £25"], what: "あらゆる分野・テーマの作品を受付。Main Prizeは£10,000、主要な公的ギャラリーでのグループ展、Aesthetica誌掲載。1エントリー2点まで。", why: "ジャンルを問わず出せる国際公募。平面・金属・mixed media・インスタ案を横断的に見せられる。", fee: "通常応募は2025/12/1〜2026/10/11で£25（10/12〜18は£35）。", url: "https://aestheticamagazine.com/artprize/" },
        { id: "arte-laguna-prize-21", title: "Arte Laguna Prize（第21回）", org: "Arte Laguna（伊・ヴェネツィア）｜国際・公募賞", deadline: "2026/06/30", cv: "mid", cvText: "中。ヴェネツィアでの入選者展。多分野対応で、ジャンル横断の作品をそのまま出せる。", tags: ["多分野対応", "登録料あり（有料）"], what: "ヴェネツィア拠点の国際現代美術コンペ。絵画・彫刻/インスタ・写真・映像・パフォーマンス・デジタル・land art・urban art・art design 等を対象。世界中の新興作家が対象。", why: "ジャンル横断の作品を出せる数少ない国際公募。金属・転写・インスタ案を主役に。", fee: "締切は2026/6/30。参加には登録料が必要（有料公募）。", url: "https://www.artelagunaprize.com/" },
        { id: "beers-london-2026", title: "BEERS London – Group Exhibition 2026", org: "BEERS London｜海外・グループ展＋レジデンス枠", deadline: "2026/08/01", cv: "mid", cvText: "中〜高。ロンドンのギャラリー主催の選抜グループ展。海外展示歴になる。", tags: ["全メディア対象", "応募料 £10"], what: "全メディア対象の若手向けグループ展。約12名を選出し、2026年10月にロンドンで開催。40日間レジデンス枠との同時応募も可能。", why: "引き継ぎ書でも海外若手導線として挙がっていた先。素材・支持体へ展開する作家として出せる。", fee: "締切は2026/8/1。応募料は展示のみ£10／展示＋レジデンス£25。", url: "https://opencall.beerslondon.com/" },
        { id: "nomad-art-prize-2026", title: "Nomad Art Prize 2026（リスボン）", org: "Nomad Art Prize（ポルトガル）｜海外・賞＋レジデンス", deadline: "2026/07/30", cv: "mid", cvText: "中。8名選出で各€1,000＋リスボン1週間レジデンス（往復渡航・宿泊全額）＋LX Factory展。渡航込みは魅力。", tags: ["メディア不問", "16歳以上", "応募料 €50"], what: "16歳以上・国籍不問、1〜3点で応募。テーマは移動・移転・根と移動の緊張。選出8名は€1,000＋リスボン滞在（渡航・宿泊込み）＋2026/10のグループ展。", why: "都市・移動・見過ごされる存在という主題と接続。ジャンル横断の作品で出せ、渡航込みレジデンスが付く。", fee: "締切は2026/7/30。応募料€50（提出点数で段階制）。", url: "https://nomadartprize.com/" },
        { id: "vh-award-7", title: "Hyundai Motor Group – The 7th VH AWARD", org: "Hyundai Motor Group｜国際・メディアアート賞", deadline: "2026/07/21", cv: "high", cvText: "高（主軸はメディアアート）。通れば強いが映像・デジタル寄り。挑戦枠。", tags: ["メディアアート", "アジアの文脈"], what: "アジアの文脈に関わる新興メディアアーティスト対象の国際賞。制作グラント、Ars Electronicaでのオンラインレジデンス、世界各地での展示。グランプリは追加$30,000。", why: "写真の物質化・反射・透明面を映像／デジタル／インスタへ展開できるなら挑戦余地。ジャンル横断の射程を試す枠。", fee: "締切は2026/7/21。", url: "https://vhaward.com/" }
      ]
    },
    {
      label: "C. 海外｜レジデンス・サイトスペシフィック（受付中）",
      items: [
        { id: "wells-art-contemporary-2026", title: "Wells Art Contemporary 2026", org: "Wells Cathedral（英）｜海外・公募／サイトスペシフィック", deadline: "2026/06/30", cv: "mid", cvText: "中〜高。ウェルズ大聖堂での展示。サイトスペシフィック部門があり、祈り・支持体の主題と空間が強く接続。海外輸送・設営の負担は要考慮。", tags: ["サイトスペシフィック可", "メディア不問"], what: "ウェルズ大聖堂で100点超を展示。2部門：『Site-Specific Installations（内外への設置提案）』締切6/30・£30／『Gallery（2D・3D作品）』締切8/11・£20。1作家最大4点。展示2026/10/10〜11/7。", why: "祈り・不在・支持体の主題と大聖堂空間が強く接続。サイトスペシフィックなインスタ案をそのまま提案できる。", fee: "Site-specific £30／Gallery £20（26歳未満の美大生は£12）。", url: "https://www.wellsartcontemporary.co.uk/for-artists" },
        { id: "wassaic-project-2027", title: "Wassaic Project 2027 Artist Residencies", org: "Wassaic Project（米NY州）｜国際・レジデンス", deadline: "2026/07/01", cv: "mid", cvText: "中〜高。制度的な国際レジデンス歴になる。渡航費負担を考慮。", tags: ["分野不問", "国際可", "応募料 $25"], what: "夏季・冬季のオンサイト・レジデンス（単一公募で両季を受付）。版・紙・金属・素材系の制作環境。費用はスライド制$0〜$900。2027夏は6〜9月の各期。", why: "写真を支持体・素材・立体へ展開する制作を深める滞在。国際レジデンス歴は『プロジェクト実施力』を示す材料になる。", fee: "締切は2026/7/1。応募料$25（経済的事情で免除可）。渡航費は自己負担。", url: "https://wassaicproject.org/apply" },
        { id: "hosq-notations-2", title: "hosq Notations #2（アルメニア）", org: "hosq（アルメニア）｜国際・リサーチ＋設置型フェス", deadline: "2026/06/10", cv: "mid", cvText: "中。音・メディア・インスタ・パフォーマンス・リサーチ横断のラボ＆フェス。テーマ『rituals（儀礼）』が作風に直結。締切間近。", tags: ["分野横断", "テーマ:儀礼", "締切間近"], what: "テーマは儀礼（rituals）。11日間のリサーチ・制作期間を経て、フェスでインスタレーションとして発表する横断型プログラム。", why: "祈り・形骸化した行為・儀礼という主題に直結。国際的な設置型プロジェクトの実績になる。", fee: "締切は2026/6/10。", url: "https://hosq.co" }
      ]
    }
  ],
  upcoming: [
    { id: "mimoca-eye-vol2", title: "第2回 MIMOCA EYE", org: "丸亀市猪熊弦一郎現代美術館｜国内・美術館個展機会", opens: "2026/07/15", deadline: "2026/09/15", cv: "high", tags: ["36歳以下", "活動歴概ね3年以上", "ジャンル不問"], what: "現代美術館での個展機会が付く公募。ジャンル不問。応募資格は『2026/4/1時点で36歳以下・活動歴概ね3年以上・美術館での個展未経験』。応募は無料（制作・出品費は自己負担）。", url: "https://www.mimoca.jp/mimoca-eye/vol2/" },
    { id: "scarts-koubo-2027", title: "SCARTS企画公募2027", org: "札幌文化芸術交流センターSCARTS｜国内・企画公募", opens: "2026/06/15", deadline: "2026/07/17", cv: "mid", tags: ["年齢・居住・拠点不問", "ジャンル自由"], what: "SCARTSの施設・備品を提供して企画の実現を後押しする公募。対象は文化芸術活動を行う団体・個人（年齢・居住・拠点不問）、ジャンル自由。受付は2026/6/15〜7/17必着。", url: "https://www.sapporo-community-plaza.jp/scartskoubo.html" },
    { id: "asahi-art-grant-2027", title: "朝日新聞文化財団 芸術活動助成（美術・2027年度）", org: "朝日新聞文化財団｜国内・助成", opens: "2026/07/01", deadline: "2026/10/25", cv: "mid", tags: ["展覧会・プロジェクト助成"], what: "2027年度(2027/4〜2028/3実施)の美術分野の活動への助成。受付は2026/7/1〜10/25。今後の個展・プロジェクトの資金計画に組み込める。", url: "https://www.asahizaidan.or.jp/grant/grant01.html" }
  ],
  openings: [
    { id: "takaishii-kyoto-anastassiades-2026", gallery: "タカ・イシイギャラリー 京都", area: "京都", title: "マイケル・アナスタシアデス「From Warm Yellow to Saturated Red」", artist: "Michael Anastassiades", when: "レセプション 2026/6/6（土）15:30–17:30", date: "2026/06/06", note: "会期 2026/6/6–7/4（京都）", url: "https://www.takaishiigallery.com/jp/", tags: ["レセプション時間あり"] },
    { id: "shugoarts-toya-2026", gallery: "ShugoArts（シュウゴアーツ）", area: "東京・六本木", title: "戸谷成雄追悼展「彫刻家・戸谷成雄」", artist: "戸谷成雄", when: "オープン 2026/6/6（土）", date: "2026/06/06", address: "東京都港区六本木6-5-24 complex665 2F", note: "会期 2026/6/6–6/27（六本木）", url: "https://shugoarts.com/", tags: [] },
    { id: "kosakukanechika-aoki-2026", gallery: "KOSAKU KANECHIKA", area: "東京・京橋", title: "青木豊「節とつぶて」", artist: "青木豊", when: "オープン 2026/6/12（金）", date: "2026/06/12", note: "会期 2026/6/12–7/25（京橋）", url: "https://kosakukanechika.com/", tags: [] },
    { id: "takaishii-roppongi-gokita-2026", gallery: "タカ・イシイギャラリー 六本木", area: "東京・六本木", title: "五木田智央「Lush Life」", artist: "五木田智央", when: "レセプション 2026/6/27（土）17:00–19:00", date: "2026/06/27", note: "会期 2026/6/27–7/25（六本木・京橋）", url: "https://www.takaishiigallery.com/jp/", tags: ["レセプション時間あり"] }
  ],
  onview: [
    { id: "onview-koyama-kyobashi-ahn", gallery: "小山登美夫ギャラリー京橋", area: "東京・京橋", title: "アン・ジサン「昼、夜」", artist: "アン・ジサン", dates: "2026/4/25–6/6", ends: "2026/06/06", url: "https://www.tokyoartbeat.com/events/-/Ahn-Jisan-Day-Night/tomio-koyama-gallery-kyobashi/2026-04-25", tags: ["#絵画・平面"] },
    { id: "onview-foam-matsuoka", gallery: "FOAM CONTEMPORARY", area: "東京・銀座", title: "Yohta Matsuoka「Life on the Table」", artist: "松岡陽太", dates: "2026/5/23–6/10", ends: "2026/06/10", url: "https://www.tokyoartbeat.com/events/-/Yohta-Matsuoka-Life-on-the-Table/foam-contemporary/2026-05-23", tags: ["#絵画・平面"] },
    { id: "onview-koyama-roppongi-neto", gallery: "小山登美夫ギャラリー六本木", area: "東京・六本木", title: "エルネスト・ネト「Dreaming Beings」", artist: "Ernesto Neto", dates: "2026/5/2–6/13", ends: "2026/06/13", url: "https://www.tokyoartbeat.com/events/-/Ernesto-Neto-Dreaming-Beings/53785-C88/2026-05-02", tags: ["#彫刻・立体"] },
    { id: "onview-takaishii-okuyama", gallery: "タカ・イシイギャラリー フォトグラフィー/フィルム", area: "東京・六本木", title: "奥山由之「photographs」", artist: "奥山由之", dates: "2026/5/15–6/13", ends: "2026/06/13", url: "https://www.tokyoartbeat.com/events/-/Yoshiyuki-Okuyama-Photographs/1-A21-DB-85/2026-05-15", tags: ["#写真"] },
    { id: "onview-voidplus-koromo", gallery: "void+（ヴォイドプラス）", area: "東京・青山", title: "衣真一郎「石室」", artist: "衣真一郎", dates: "2026/5/16–6/13", ends: "2026/06/13", url: "https://www.tokyoartbeat.com/events/-/Shinichiro-Koromo-Stone-Chamber/15-E4-AC-9-F/2026-05-16", tags: ["#絵画・平面"] },
    { id: "onview-maki-ando", gallery: "Maki Fine Arts", area: "東京・神楽坂", title: "安藤由莉「Rendering」", artist: "安藤由莉", dates: "2026/5/16–6/14", ends: "2026/06/14", url: "https://www.tokyoartbeat.com/events/-/Yuri-Ando-Rendering/975-EFF-82/2026-05-16", tags: ["#絵画・平面"] },
    { id: "onview-takaishii-yamashita", gallery: "タカ・イシイギャラリー京橋", area: "東京・京橋", title: "山下紘加「白気 White Veils」", artist: "山下紘加", dates: "2026/5/16–6/20", ends: "2026/06/20", url: "https://www.tokyoartbeat.com/events/-/Hiroka-Yamashita-White-Veils/taka-ishii-gallery-kyobashi/2026-05-16", tags: ["#絵画・平面"] },
    { id: "onview-standingpine-leeufan", gallery: "STANDING PINE 東京", area: "東京・天王洲", title: "李禹煥 + クロード・ヴィアラ + ジャンフランコ・ザッペティーニ 展", artist: "李禹煥 ほか", dates: "2026/5/23–6/20", ends: "2026/06/20", url: "https://www.tokyoartbeat.com/events/-/Lee-Ufan-Claude-Viallat-Gianfranco-Zappettini-Exhibition/standing-pine-tokyo/2026-05-23", tags: ["#絵画・平面"] },
    { id: "onview-spaceun-roy", gallery: "space Un", area: "東京・青山", title: "アンリ・ロア「DEVOTION」", artist: "Henry Roy", dates: "2026/4/25–6/21", ends: "2026/06/21", url: "https://www.tokyoartbeat.com/events/-/Henry-Roy-Devotion/space-un/2026-04-25", tags: ["#写真"] },
    { id: "onview-igallery-nordstroem", gallery: "i GALLERY", area: "大阪", title: "C.R. ノルドストローム/東京ビルド「Iteration（反復）」", artist: "Christopher Robin Nordström", dates: "2026/5/23–6/22", ends: "2026/06/22", url: "https://www.tokyoartbeat.com/events/-/Christopher-Robin-Nordstroem-Tokyo-Build-Iteration/i-gallery/2026-05-23", tags: ["関西", "#彫刻・立体"] },
    { id: "onview-kayokoyuki-suwa", gallery: "KAYOKOYUKI", area: "東京・六本木", title: "諏訪未知「PANTALOON」", artist: "諏訪未知", dates: "2026/5/23–6/27", ends: "2026/06/27", url: "https://www.tokyoartbeat.com/events/-/Michi-Suwa-Pantaloon/E0-E4379-E/2026-05-23", tags: ["#絵画・平面"] },
    { id: "onview-kennakahashi-landscape", gallery: "KEN NAKAHASHI", area: "東京・新宿", title: "「In a Landscape」", artist: "グループ展", dates: "2026/4/10–6/27", ends: "2026/06/27", url: "https://www.tokyoartbeat.com/events/-/In-a-Landscape/C1768938/2026-04-10", tags: ["#絵画・平面"] },
    { id: "onview-poeticscape-endo", gallery: "POETIC SCAPE", area: "東京・中目黒", title: "遠藤文香「Kanoko」", artist: "遠藤文香", dates: "2026/5/16–6/28", ends: "2026/06/28", url: "https://www.tokyoartbeat.com/events/-/Ayaka-Endo-Kanoko/5-C2060-D7/2026-05-16", tags: ["#写真"] },
    { id: "onview-koyanagi-marclay", gallery: "ギャラリー小柳", area: "東京・銀座", title: "クリスチャン・マークレー「LISTENING」", artist: "Christian Marclay", dates: "2026/4/4–6/30", ends: "2026/06/30", url: "https://www.tokyoartbeat.com/events/-/Christian-Marclay-Listening/5693-F25-A/2026-04-04", tags: ["#絵画・平面"] },
    { id: "onview-snow-fuse", gallery: "SNOW Contemporary", area: "東京・六本木", title: "布施琳太郎「タイムトラベラーのための展覧会」", artist: "布施琳太郎", dates: "2026/5/22–7/4", ends: "2026/07/04", url: "https://www.tokyoartbeat.com/events/-/Rintaro-Fuse-Exhibition-for-Time-Travelers/B203-D9-DE/2026-05-22", tags: ["#映像・映画"] },
    { id: "onview-fergus-fischer", gallery: "ファーガス・マカフリー 東京", area: "東京・青山", title: "ウルス・フィッシャー「間違い探し」", artist: "Urs Fischer", dates: "2026/4/11–7/5", ends: "2026/07/05", url: "https://www.tokyoartbeat.com/events/-/Urs-Fischer-Machigai-Sagashi-Spot-the-Difference/E622-CDFE/2026-04-11", tags: ["#インスタレーション"] },
    { id: "onview-gyre-spectrum", gallery: "GYRE GALLERY", area: "東京・表参道", title: "「SPECTRUM 2076 AD ── 来たる世界の意識体」", artist: "グループ展", dates: "2026/5/22–7/12", ends: "2026/07/12", url: "https://www.tokyoartbeat.com/events/-/Spectrum-2076-AD-Conscious-Entities-of-the-Coming-World/886471-D5/2026-05-22", tags: [] },
    { id: "onview-kikutake-nerhol", gallery: "Yutaka Kikutake Gallery", area: "東京・六本木", title: "Nerhol「Unseen Body」", artist: "Nerhol", dates: "2026/5/23–7/18", ends: "2026/07/18", url: "https://www.tokyoartbeat.com/events/-/Nerhol-Unseen-Body/11-B9-DD-0-F/2026-05-23", tags: [] },
    { id: "onview-suchsize-hayakawa-onishi", gallery: "SUCHSIZE（サッチサイズ）", area: "大阪", title: "早川祐太 + 大西伸明「drifting elements」", artist: "早川祐太 / 大西伸明", dates: "2026/4/17–6/13", ends: "2026/06/13", url: "https://www.tokyoartbeat.com/events/-/Yuta-Hayakawa-Nobuaki-Onishi-Drifting-Elements/suchsize/2026-04-17", tags: ["関西", "#彫刻・立体"] },
    { id: "onview-kouichi-ryczek", gallery: "KOUICHI FINE ARTS", area: "大阪", title: "マルチン・リチェク「ハーモニー」", artist: "Marcin Ryczek", dates: "2026/5/11–6/13", ends: "2026/06/13", url: "https://www.tokyoartbeat.com/events/-/Marcin-Ryczek-Harmony/kouichi-fine-arts/2026-05-11", tags: ["関西", "#写真"] },
    { id: "onview-plusy-kitatsuji", gallery: "+Y Gallery", area: "大阪", title: "北辻良央 展", artist: "北辻良央", dates: "2026/5/19–6/12", ends: "2026/06/12", url: "https://www.tokyoartbeat.com/events/-/Yoshihisa-Kitatsuji-Exhibition/y-gallery/2026-05-19", tags: ["関西", "#彫刻・立体"] },
    { id: "onview-parco-osaka-igarashi", gallery: "PARCO GALLERY OSAKA", area: "大阪", title: "「A–Z Homage to Takenobu Igarashi」", artist: "五十嵐威暢 ほか", dates: "2026/5/22–6/14", ends: "2026/06/14", url: "https://www.tokyoartbeat.com/events/-/A-Z-Homage-to-Takenobu-Igarashi/parco-gallery-osaka/2026-05-22", tags: ["関西"] },
    { id: "onview-tezukayama-resonance", gallery: "TEZUKAYAMA GALLERY", area: "大阪", title: "「律動のレゾナンス」", artist: "グループ展", dates: "2026/5/23–6/20", ends: "2026/06/20", url: "https://www.tokyoartbeat.com/events/-/Resonance-of-Rhythm/CEB-8-D156/2026-05-23", tags: ["関西", "#絵画・平面"] },
    { id: "onview-tezukayama-kato", gallery: "TEZUKAYAMA GALLERY", area: "大阪", title: "加藤智大「The face speaks」", artist: "加藤智大", dates: "2026/5/23–6/20", ends: "2026/06/20", url: "https://www.tokyoartbeat.com/events/-/Tomohiro-Kato-The-face-speaks/CEB-8-D156/2026-05-23", tags: ["関西", "#彫刻・立体"] },
    { id: "onview-artcourt-ishizuka", gallery: "ARTCOURT Gallery", area: "大阪", title: "石塚源太 作品集出版記念展「Relative Dimension」", artist: "石塚源太", dates: "2026/5/23–6/27", ends: "2026/06/27", url: "https://www.tokyoartbeat.com/events/-/Genta-Ishizuka-Relative-Dimension-Book-Launch-Exhibition/artcourt-gallery/2026-05-23", tags: ["関西", "#陶芸・漆"] },
    { id: "onview-isseymiyake-semba-nishimura", gallery: "ISSEY MIYAKE SEMBA | CREATION SPACE", area: "大阪", title: "西村陽一郎「光がふれる、折りとかたち」", artist: "西村陽一郎", dates: "2026/5/1–6/27", ends: "2026/06/27", url: "https://www.tokyoartbeat.com/events/-/Yoichiro-Nishimura-Touched-by-Light-Folds-and-Forms/issey-miyake-semba-creation-space/2026-05-01", tags: ["関西", "#インスタレーション"] },
    { id: "onview-hillgate-kusui", gallery: "ギャラリーヒルゲート", area: "京都", title: "楠井沙耶「かかる木」", artist: "楠井沙耶", dates: "2026/1/12–6/14", ends: "2026/06/14", url: "https://www.tokyoartbeat.com/events/-/Saya-Kusui-The-leaning-tree/gallery-hillgate/2026-01-12", tags: ["関西", "#彫刻・立体"] },
    { id: "onview-sokyo-narita", gallery: "SOKYO（祇園）", area: "京都", title: "成田輝「最小限の断片」", artist: "成田輝", dates: "2026/5/14–6/11", ends: "2026/06/11", url: "https://www.tokyoartbeat.com/events/-/Hikaru-Narita-Minimal-Fragments/sokyo/2026-05-14", tags: ["関西", "#彫刻・立体"] },
    { id: "onview-nonakahill-idetsu", gallery: "ノナカ・ヒル京都", area: "京都", title: "出津京子「酷暑」", artist: "出津京子", dates: "2026/5/16–7/11", ends: "2026/07/11", url: "https://www.tokyoartbeat.com/events/-/Kyoko-Idetsu-Extreme-Heat/nonaka-hill-kyoto/2026-05-16", tags: ["関西", "#絵画・平面"] },
    { id: "onview-leica-kyoto-freitas", gallery: "ライカギャラリー京都", area: "京都", title: "テレサ・フレイタス「Colour Matter(s)」", artist: "Teresa Freitas", dates: "2026/5/16–7/19", ends: "2026/07/19", url: "https://www.tokyoartbeat.com/events/-/Teresa-Freitas-Colour-Matter-s/leica-gallery-kyoto/2026-05-16", tags: ["関西", "#写真"] },
    { id: "onview-hosoo-gates", gallery: "HOSOO GALLERY", area: "京都", title: "シアスター・ゲイツ「Glorious Robe」", artist: "Theaster Gates", dates: "2026/4/11–8/30", ends: "2026/08/30", url: "https://www.tokyoartbeat.com/events/-/Theaster-Gates-Glorious-Robe/3-C499056/2026-04-11", tags: ["関西", "#インスタレーション"] },
    { id: "onview-galleryten-takiguchi", gallery: "ギャラリー点", area: "京都", title: "瀧口修造「『妖精の距離』と『スフィンクス』」", artist: "瀧口修造", dates: "2026/4/25–7/26", ends: "2026/07/26", url: "https://www.tokyoartbeat.com/events/-/Shuzo-Takiguchi-Distance-of-a-Fairy-and-Sphinx/gallery-ten/2026-04-25", tags: ["関西", "#絵画・平面"] },
    { id: "onview-alab-tsuchiya", gallery: "A-LAB", area: "兵庫・尼崎", title: "土屋咲瑛「→第4の壁」", artist: "土屋咲瑛", dates: "2026/5/2–6/28", ends: "2026/06/28", url: "https://www.tokyoartbeat.com/events/-/Sae-Tsuchiya-The-Fourth-Wall/DB-28-ED-8-B/2026-05-02", tags: ["関西", "地元", "#絵画・平面"] }
  ],
  top3: [
    { title: "Future Generation Art Prize 2027", note: "（6/28・無料・メディア不問の国際大本命）ジャンル横断の目標に直結。最優先。" },
    { title: "Wells Art Contemporary 2026", note: "（6/30・サイトスペシフィック部門）大聖堂空間に祈り・支持体の主題を直接展開できる。インスタ案を出せる希少な機会。" },
    { title: "中之条ビエンナーレ2027", note: "（7/12・芸術祭）採択が現実的で、実物の展示経験＋展示風景写真を作れる。" }
  ],
  excluded: [
    "遊工房アートスペース レジデンス … 体制変更により閉鎖（恒久終了）。",
    "岡本太郎現代芸術賞（TARO賞）… 公式に現在の募集・締切の記載がないため掲載せず（次回募集を監視）。",
    "KAF Young Prize 2026（締切3/31）／ACTアート大賞展（2/8）／アイスタイル財団 助成（1/31）／BBA Artist Prize（2025/12/8）… 受付終了。",
    "小笠原敏晶記念財団 助成 … 2026年度は募集前（調整中）。前年実績では7〜9月募集。",
    "Hiroshima MoCA FIVE 25/26／TOKAS-Emerging／Tokyo Contemporary Art Award … 前回受付終了。次回を監視（TCAAは活動歴10年以上が対象で現段階は対象外）。",
    "CAF賞（学生限定）／Circulation(s)（欧州在住限定）／STPLN(Culture Moves Europe対象国在住限定)／The Bennett Prize（女性限定）… 応募資格の対象外。"
  ],
  disclaimer: "掲載は本日（2026/6/7）に応募ページ・募集要項まで確認したものです。締切間際の変更等が生じた場合は各公式ページが優先します。"
};
