// 毎朝9時のタスクがこのファイルを丸ごと書き換えます。
// index.html はこの window.OPENCALLS を読んでカードを描画します。
// 掲載基準：本日時点で公式ページ（応募ページ/募集要項）または信頼できる一次的告知で「受付中（受付期間が開始済み）」＋締切を確認できたものだけ。
window.OPENCALLS = {
  date: "2026年6月23日（火）",
  updated: "2026-06-23",
  intro: "本日（2026/6/23）もWebFetchツールが環境側の障害で全URL（google.com・example.com等の無関係な大手サイトを含む）に対して403を返す状態が4日連続で継続しており、主催公式ページへブラウザ的に直接アクセスすることはできませんでした。そのため本日はWebSearchツールを用い、各主催の公式ページの内容を検索結果として直接確認する方式で代替検証を実施。締切が近い5件（Future Generation Art Prize 2027・Berlin Photo Awards 2026・熊谷正寿文化財団助成・Arte Laguna Prize・Wells Art Contemporary）は公式情報に変更がないことを確認。さらに新たに4件（Brillia Art Award Wall 2026・R.E. Award 2026・Arteventura Artist Residency 2027・SIAF2027 500m美術館賞）を公式情報で受付中と確認して『受付中』セクションへ、TOKAS-Emerging 2027・FACE 2027の2件を受付開始前として『まもなく受付開始』へ追加。過去に確認不足で見送っていた候補のうち、SCARTS企画公募2027・岡本太郎現代芸術賞次回・小笠原敏晶記念財団助成・アーツサポート関西次回・兵庫県展2026は次回募集が未発表のため引き続き見送り、U25 Art Contest 2026は応募締切の出典が矛盾し確定できないため見送り、Beautiful Bizarre Art Prize 2026は作風の方向性が合わないため見送り。その他既存項目は2026/6/19の公式確認内容を、締切経過チェック（本日時点で経過した締切なし）のうえ引き継いでいます。受付開始前は『まもなく受付開始』に分離。林稔里をジャンル横断の現代アーティストとして選定。提出済み（GRID NEXT / FF Seoul / NCA / SUBTEXT / YAU / MIDTOWN / SUPERGAU / Saatchi）は除外。",
  sections: [
    {
      label: "A. 国内｜芸術祭・賞・助成・レジデンス（受付中）",
      items: [
        { id: "nakanojo-biennale-2027", title: "中之条ビエンナーレ2027", org: "中之条ビエンナーレ実行委員会｜国内・国際芸術祭", deadline: "2026/07/12", cv: "high", cvText: "高。実空間で発表でき、実物の展示経験と展示風景写真を作れる。採択も現実的。", tags: ["メディア不問", "実物展示", "滞在制作"], what: "群馬県中之条町で隔年開催の国際現代芸術祭。会期2027/9/18〜10/24。山村地域のAIRで滞在制作し成果を発表。多分野を公募。", why: "写真を金属・反射・透明面・公共空間へ展開するインスタ案を、初めて実物として設置できる機会。ジャンル横断の実践を空間でそのまま見せられる。", fee: "Web応募は2026/7/12 23:59まで、郵送は当日消印有効。", url: "https://nakanojo-biennale.com/2027-open-call" },
        { id: "idemitsu-art-award-2026", title: "Idemitsu Art Award 2026（出光アートアワード）", org: "出光興産｜国内・公募賞", deadline: "2026/07/31", cv: "high", cvText: "高。国内の若手登竜門。入選でもギャラリー営業で説明しやすい。", tags: ["1986/4/1以降生まれ", "平面のみ"], what: "旧シェル美術賞。平面作品（絵画・写真・布・刺繍・レリーフ等、ワイヤー吊り展示可）対象。立体・映像・共同制作は不可。グランプリ300万円、入選40〜50点。", why: "《片染め》や転写・mixed mediaの平面で出せる。写真に限らず支持体や素材の扱いを含めて『平面の現代美術』として見せる。", fee: "エントリーは6/1〜7/31（オンライン）、搬入8/20〜23。応募料は25歳以下は無料〜¥11,000。", url: "https://www.idemitsu.com/jp/fun/art/method.html" },
        { id: "kumagai-grant-2026", title: "熊谷正寿文化財団 現代アート作家助成", org: "熊谷正寿文化財団｜国内・制作助成", deadline: "2026/06/30", cv: "mid", cvText: "中。最大100万円の制作助成。受給は実制作の後押しになり、助成歴はCVにも効く。", tags: ["35歳以下", "制作経験3年以上", "原材料費が主対象"], what: "現代アートの制作を支援する助成。助成額は100万円まで。主に作品の原材料費が対象（会場費・生活費は除外）。活動期間は2026/9/1〜2027/8/31。", why: "金属・反射・透明面・立体の実制作の資金になる。応募資格は『募集年度4/1時点で35歳以下・現代アート制作経験3年以上』。", fee: "募集は2026/5/1〜6/30（必着）。", url: "https://kumagai.art/subsidies/" },
        { id: "l-air-2026-himeji", title: "L-AIR 2026（姫路・兵庫）", org: "一般社団法人 L-A・I・R｜国内・レジデンス", deadline: "随時受付中", cv: "mid", cvText: "中〜高。地元・兵庫で渡航負担なし。皮革＝支持体・労働・身体と接続でき作風適合。", tags: ["兵庫・地元", "随時受付", "分野横断"], what: "姫路市高木（皮革産地）のレジデンス。皮革を素材に新しい表現を探究する、分野を超えたアーティストが対象。1.5〜3か月の住み込み制作（皮革提供・フィールドリサーチ・月額最大25万円の制作支援あり）で随時受付。", why: "写真プリント・手彩色・擦過・皮革支持体・立体を組み合わせ、都市・労働・身体・素材を横断的に扱える。", fee: "応募はメールにて（件名「L-AIR Artist Apply」）。詳細はアーティスト募集ページから。", url: "https://l-air.or.jp/artist_apply/" },
        { id: "holbein-scholarship-39", title: "ホルベイン・スカラシップ奨学生（第39回）", org: "ホルベイン｜国内・制作支援（画材提供）", deadline: "2026/07/31", cv: "low", cvText: "低。展示歴ではなく画材支援。CV価値は小さいが制作の実利が大きい。", tags: ["18〜45歳", "国内在住", "画材支援"], what: "色材を使用した制作を行う18〜45歳・日本国内在住者対象。最大7名に総額30万円相当の絵具・筆・キャンバス等を3回に分けて提供。奨学期間2026/12〜2027/11。", why: "《片染め》・オイルスティック作品の画材コストを実質的に下げられる。応募料は無料。", fee: "締切は2026/7/31 12:00。応募無料。", url: "https://www.holbein.co.jp/scholarship/" },
        { id: "art-olympia-2026", title: "ART OLYMPIA 2026", org: "ART OLYMPIA実行委員会｜国内発・国際公募展", deadline: "2026/07/31", cv: "high", cvText: "高。グランプリ1000万円という大型賞金と国際的な展示機会のある公募。年齢制限なし（全応募者部門）。", tags: ["平面のみ", "壁面展示", "年齢不問"], what: "油彩・日本画・版画・水彩・写真・ミクストメディア等、壁面展示可能な平面作品が対象（サイズ117×117cm以内・厚さ10cm以内・重量20kg以内）。立体・映像・AI使用・共同制作は不可。応募受付期間は2026/4/1〜7/31、会期は2026年11月。", why: "写真・転写・金属を組み合わせた壁面mixed media作品として《片染め》などの平面シリーズを国際公募の大型賞に出せる。", fee: "締切は2026/7/31。応募料は1点12,000円〜（部門・点数により変動）。", url: "https://artolympia.jp/" },
        { id: "shinkyo-kansai-art-compe-5", title: "第5回 関西アートコンペ（新協美術会）", org: "一般社団法人 新協美術会｜国内・関西公募展", deadline: "2026/09/20", cv: "mid", cvText: "中。地元・関西（大阪）で発表できる公募展。彫刻・工芸部門に金属・mixed mediaの立体作品を出せる。", tags: ["関西・大阪", "彫刻・工芸部門あり", "年齢不問"], what: "第69回新協美術会関西巡回展と併催の公募展。絵画・彫刻・工芸・写真の4部門、年齢・経験不問。会期は2026/10/20〜25、会場は天王寺ギャラリー（大阪市立美術館）。", why: "金属・転写・mixed mediaの立体作品を彫刻・工芸部門に出品し、地元関西での展示実績を作れる。", fee: "締切は2026/9/20。参加費は一般4,500円（直接搬出は4,000円）。", url: "https://www.shinkyoart.or.jp/" },
        { id: "art-award-in-the-cube-2027", title: "Art Award IN THE CUBE 2027（清流の国ぎふ芸術祭）", org: "岐阜県・岐阜県美術館｜国内・公募展（インスタレーション形式）", deadline: "2026/07/10", cv: "high", cvText: "非常に高。幅4.8m×奥行4.8m×高さ3.6mの専用キューブ空間にインスタレーションを設計できる公募。大賞500万円、入選約10点にも製作支援60万円。サイトスペシフィックな実践を国内最大規模で発表できる。", tags: ["年齢・国籍不問", "インスタレーション専用空間", "新作限定"], what: "テーマは『なやんでうごけ 創造の水脈を探して』。幅4.8m×奥行4.8m×高さ3.6mのキューブ空間での新作インスタレーションを1人/1組につき1点で公募。大賞500万円、奨励賞各100万円、入選約10点に製作支援60万円。応募期間は2026/3/18〜7/10。", why: "写真・金属・転写・mixed mediaを横断するサイトスペシフィックなインスタ案を、専用の大型キューブ空間でそのまま実現できる。賞金規模・支援体制も国内最大級。", fee: "締切は2026/7/10 23:59。", url: "https://www.aaic.pref.gifu.lg.jp/application" },
        { id: "myoju-residency-fellowship-2026", title: "Myoju Residency Fellowship（近江八幡）", org: "MYOJU｜国内・レジデンス（フェローシップ）", deadline: "2026/07/05", cv: "mid", cvText: "中〜高。京都近郊・近江八幡での4週間レジデンス。渡航負担が少なく、滞在費・スタジオは主催側が提供（応募料無料）。", tags: ["応募無料", "滞在費・スタジオ提供", "ビジュアルアート対象"], what: "京都近郊（滋賀県近江八幡市・琵琶湖畔の歴史的商家町）でのレジデンス。ビジュアルアート・文芸・メディア/デジタルアート・キュレーション分野が対象。2026/9/1〜28の4週間、滞在費・スタジオは主催側が提供（渡航費・食費・保険等は自己負担）。記憶・アイデンティティ・再生をテーマに地域との対話を重視。", why: "関西圏（滋賀・京都）での滞在制作機会で、渡航負担が小さい。写真・転写・mixed mediaを地域文脈の中で展開できる。応募料は無料。", fee: "締切は2026/7/5。応募無料（滞在費・スタジオ提供、渡航費等は自己負担）。", url: "https://myoju.com/pages/air" },
        { id: "fugensha-photo-award-6", title: "第6回 ふげん社写真賞", org: "ふげん社｜国内・写真賞", deadline: "2026/08/30", cv: "mid", cvText: "中〜高。グランプリは写真集出版＋記念展示。年齢・国籍・プロアマ不問で挑戦しやすく、二次選考（東京都写真美術館）を通じて発表機会も得られる。", tags: ["年齢・国籍不問", "プロアマ不問", "写真集出版"], what: "プロ・アマチュア、年齢・国籍不問の写真賞。グランプリは写真集の出版＋記念展示。選考委員は飯沢耕太郎・鷹野隆大・野村恵子ら。二次選考は2026/10/18に東京都写真美術館で開催。応募期間は2026/6/3〜8/30 18:00。", why: "写真を起点に転写・mixed mediaへ展開する作風の『写真』パートを、国内の主要な写真賞の文脈で発表できる。", fee: "締切は2026/8/30 18:00。", url: "https://www.fugensha.jp/events/award6" },
        { id: "brillia-art-award-wall-2026", title: "Brillia Art Award Wall 2026", org: "東京建物｜国内・公募展（平面）", deadline: "2026/07/08", cv: "mid", cvText: "中。賞金20万円×2点＋『Brillia Gallery 新宿』エントランスでの約6か月間の展示。プロアマ・年齢・国籍不問で挑戦しやすい。", tags: ["年齢・国籍不問", "プロアマ不問", "平面のみ", "郵送のみ"], what: "東京建物のマンションブランドBrilliaによる、平面作品（写真・絵画等メディア不問）対象の公募展。最大サイズ2400×1800mm・重量30kg以内。応募は郵送のみ（持ち込み不可）。応募期間は2026/5/12〜7/8。入賞2点に賞金20万円ずつ、入賞作品は『Brillia Gallery 新宿』エントランスで約6か月展示。", why: "《片染め》などの転写・mixed media平面作品を、企業ギャラリーでの半年間という長期展示機会に出せる。応募資格が広く挑戦しやすい。", fee: "締切は2026/7/8。応募料は公式サイトに明記がなく要確認。", url: "https://www.brillia-art.com/award/wall/about_application.html" },
        { id: "re-award-2026-hazi-asp", title: "R.E. Award 2026 / r.e. award 2026「Three-Point Perspective」", org: "ASP（インドネシア・ジョグジャカルタ）× project space hazi（愛知）｜国内発・国際協働レジデンス賞", deadline: "2026/07/24", cv: "mid", cvText: "中。応募無料・国籍不問の小規模だが国際協働のレジデンス賞。約1か月のリサーチ・制作機会と支援金が付く。", tags: ["応募無料", "国籍・年齢不問", "レジデンス約1か月"], what: "インドネシア・ジョグジャカルタのASPと愛知・岩倉のproject space haziが共同主催する小規模アートアワード。2026年版テーマは『Three-Point Perspective』。選出されるとASP・haziいずれか（または両方）で約1か月のリサーチ・実験・制作のレジデンス機会と最大10万円の支援を提供。レジデンス実施期間は2026/10〜2027/8。応募無料。", why: "写真を起点に転写・mixed mediaへ展開する制作を、日本とインドネシアどちらの文化的文脈でも試せる。応募無料で挑戦しやすい小規模賞。", fee: "締切は2026/7/24 24:00（JST）。応募無料。", url: "https://www.e-flux.com/announcements/6785168/open-call-artist-support-program-2026" },
        { id: "siaf2027-500m-museum-award", title: "SIAF2027 500m美術館賞 展示プラン募集", org: "札幌国際芸術祭2027（SIAF2027）／札幌大通地下ギャラリー500m美術館｜国内・国際公募（サイトスペシフィック）", deadline: "2026/07/20", cv: "high", cvText: "高。国際芸術祭SIAF2027の会場での展示機会。ガラスケース形式のサイトスペシフィックな展示プランの国際公募で、選出2組に賞金30万円＋制作費20万円、海外拠点者には渡航等支援25万円も。", tags: ["国籍不問", "年齢不問", "サイトスペシフィック", "国際芸術祭"], what: "札幌大通地下ギャラリー500m美術館が札幌国際芸術祭2027（SIAF2027、テーマ『PLANET SNOW』）の会場となることを受けた特別コンペ。展示期間はSIAF2027会期中（2027/1/16〜）。ガラスケース形式の展示空間を使ったサイトスペシフィックな展示プランを国籍・年齢不問で公募し、一次書類審査・二次面接審査を経て2組を選出。選出2組に賞金30万円＋制作費20万円、海外拠点者には渡航等支援25万円。", why: "写真・金属・転写・mixed mediaを横断するサイトスペシフィックなインスタ案を、国際芸術祭の文脈でガラスケース空間に実現できる。国籍・年齢不問で挑戦しやすい。", fee: "応募期間は2026/4/20〜7/20（月・祝）23:59必着。", url: "https://www.500m.jp/award/8016.html" }
      ]
    },
    {
      label: "B. 海外｜国際賞・公募（受付中）",
      items: [
        { id: "future-generation-art-prize-2027", title: "Future Generation Art Prize 2027", org: "PinchukArtCentre（キーウ）｜国際・現代美術賞", deadline: "2026/06/28", cv: "high", cvText: "非常に高。応募・ロングリストだけでも国際的射程を示せる。", tags: ["応募無料", "35歳以下", "メディア不問"], what: "35歳以下・メディア不問の国際現代美術賞。主賞US$100,000。入選者展をPinchukArtCentreで開催（2027春）。", why: "ジャンル横断の国際的現代アーティストという目標に直結。平面・金属・インスタ案の強度を併せて出す。", fee: "応募期間は2026/5/11〜6/28。応募無料。", url: "https://futuregenerationartprize.org/en/" },
        { id: "aesthetica-art-prize-2027", title: "Aesthetica Art Prize", org: "Aesthetica Magazine（英国・York）｜国際・公募賞", deadline: "2026/10/11", cv: "high", cvText: "高。英国の主要公的ギャラリーでのグループ展＋£10,000＋誌面掲載。全分野・全レベル対象。", tags: ["メディア不問", "全レベル可", "応募料 £25"], what: "あらゆる分野・テーマの作品を受付。Main Prizeは£10,000、主要な公的ギャラリーでのグループ展、Aesthetica誌掲載。1エントリー2点まで。", why: "ジャンルを問わず出せる国際公募。平面・金属・mixed media・インスタ案を横断的に見せられる。", fee: "通常応募は2025/12/1〜2026/10/11で£25（10/12〜18は£35）。", url: "https://aestheticamagazine.com/artprize/" },
        { id: "arte-laguna-prize-21", title: "Arte Laguna Prize（第21回）", org: "Arte Laguna（伊・ヴェネツィア）｜国際・公募賞", deadline: "2026/06/30", cv: "mid", cvText: "中。ヴェネツィアでの入選者展。多分野対応で、ジャンル横断の作品をそのまま出せる。", tags: ["多分野対応", "登録料あり（有料）"], what: "ヴェネツィア拠点の国際現代美術コンペ。絵画・彫刻/インスタ・写真・映像・パフォーマンス・デジタル・land art・urban art・art design 等を対象。世界中の新興作家が対象。", why: "ジャンル横断の作品を出せる数少ない国際公募。金属・転写・インスタ案を主役に。", fee: "締切は2026/6/30。参加には登録料が必要（有料公募）。", url: "https://www.artelagunaprize.com/" },
        { id: "beers-london-2026", title: "BEERS London – Group Exhibition 2026", org: "BEERS London｜海外・グループ展＋レジデンス枠", deadline: "2026/08/01", cv: "mid", cvText: "中〜高。ロンドンのギャラリー主催の選抜グループ展。海外展示歴になる。", tags: ["全メディア対象", "応募料 £10"], what: "全メディア対象の若手向けグループ展。約12名を選出し、2026年10月にロンドンで開催。40日間レジデンス枠との同時応募も可能。", why: "引き継ぎ書でも海外若手導線として挙がっていた先。素材・支持体へ展開する作家として出せる。", fee: "締切は2026/8/1。応募料は展示のみ£10／展示＋レジデンス£25。", url: "https://opencall.beerslondon.com/" },
        { id: "nomad-art-prize-2026", title: "Nomad Art Prize 2026（リスボン）", org: "Nomad Art Prize（ポルトガル）｜海外・賞＋レジデンス", deadline: "2026/07/30", cv: "mid", cvText: "中。8名選出で各€1,000＋リスボン1週間レジデンス（往復渡航・宿泊全額）＋LX Factory展。渡航込みは魅力。", tags: ["メディア不問", "16歳以上", "応募料 €50"], what: "16歳以上・国籍不問、1〜3点で応募。テーマは移動・移転・根と移動の緊張。選出8名は€1,000＋リスボン滞在（渡航・宿泊込み）＋2026/10のグループ展。", why: "都市・移動・見過ごされる存在という主題と接続。ジャンル横断の作品で出せ、渡航込みレジデンスが付く。", fee: "締切は2026/7/30。応募料€50（提出点数で段階制）。", url: "https://nomadartprize.com/" },
        { id: "vh-award-7", title: "Hyundai Motor Group – The 7th VH AWARD", org: "Hyundai Motor Group｜国際・メディアアート賞", deadline: "2026/07/21", cv: "high", cvText: "高（主軸はメディアアート）。通れば強いが映像・デジタル寄り。挑戦枠。", tags: ["メディアアート", "アジアの文脈"], what: "アジアの文脈に関わる新興メディアアーティスト対象の国際賞。制作グラント、Ars Electronicaでのオンラインレジデンス、世界各地での展示。グランプリは追加$30,000。", why: "写真の物質化・反射・透明面を映像／デジタル／インスタへ展開できるなら挑戦余地。ジャンル横断の射程を試す枠。", fee: "締切は2026/7/21。", url: "https://vhaward.com/" },
        { id: "photovogue-global-open-call-2026", title: "PhotoVogue Global Open Call 2026「Brave New Visions」", org: "Vogue Italia / PhotoVogue｜海外・国際公募（写真・マルチメディア）", deadline: "2026/09/11", cv: "mid", cvText: "中〜高。応募無料、18歳以上で国際的に開放。写真を起点とした実験的表現を世界的なファッション・写真メディアで発表できる。", tags: ["応募無料", "18歳以上", "写真・マルチメディア"], what: "「Brave New Visions: Creativity as Rebellion」をテーマに、写真・映像・マルチメディア作品を募集。Outstanding Vision Grant $6,000、Vision Grant $4,000、Rising Voice Grant $2,000の3グラント。PhotoVogue Festivalでの発表機会やVogue各国版掲載の可能性あり。応募期間は2026/5/14〜9/11。", why: "写真を起点に転写・mixed mediaへ展開する作風を、ファインアート/実験的表現のカテゴリーで国際的な写真メディアに出せる。応募無料。", fee: "締切は2026/9/11 23:59 CET。応募無料。", url: "https://site.picter.com/photovogue-brave-new-visions-global-open-call-2026" },
        { id: "berlin-photo-awards-2026", title: "Berlin Photo Awards 2026", org: "Berlin Photo Awards｜海外・国際写真公募", deadline: "2026/06/27", cv: "low", cvText: "低〜中。商業的な国際写真コンペでCV上の価値は大きくないが、応募料が比較的低額で海外公募の実績を積む足がかりになる。", tags: ["応募料 €25〜", "AI生成不可", "Fine Art部門あり"], what: "ポートレート・建築・モノクロ・コンセプチュアル・ファインアート等の部門別に作品を募集する国際写真コンペ。総額€4,000の賞金（最優秀賞€1,000、各部門賞€100）。AI生成画像は不可。締切は2026/6/27。", why: "写真を起点とした転写・mixed media作品の写真パートを、Fine Art／Conceptual部門で発表できる。", fee: "1点目€25、追加部門ごとに€10（早期割引は終了済み）。", url: "https://www.berlinphotoawards.com/" },
        { id: "larnaca-biennale-2027", title: "Larnaca Biennale 2027（ラルナカ・ビエンナーレ）", org: "Larnaca Biennale（キプロス・ラルナカ）｜海外・国際ビエンナーレ公募", deadline: "2027/03/31", cv: "mid", cvText: "中。受付期間が長く出品まで時間的余裕がある。テーマ『Metatopies: Geographies in Motion』は移動・変容を扱い、作風と接続しやすい。13以上の賞も用意。", tags: ["分野不問", "プロアマ不問", "学生可"], what: "キプロス・ラルナカで2027/10/13〜11/26開催の国際ビエンナーレ（第5回）。テーマは『Metatopies: Geographies in Motion』、地質学的・人類学的・社会的・政治的・歴史的な『移動』を主題とする作品を公募。プロ・アマチュア・学生・写真家・デザイナー・複数分野横断の実践者まで幅広く対象。受付は2026/6/1〜2027/3/31。13以上の賞を予定。", why: "都市・移動・素材の変容という主題と直結。写真・金属・転写・mixed mediaを横断する作品をそのまま提案できる、受付期間の長い国際公募。", fee: "締切は2027/3/31。登録料は公式サイト『Submit Your Artwork』ページで要確認。", url: "https://biennalelarnaca.com/submit-your-artwork/" },
        { id: "new-emergence-art-prize-2026", title: "The New Emergence Art Prize 2026", org: "New Emergence Art｜海外・国際公募賞", deadline: "2026/08/03", cv: "mid", cvText: "中。新進アーティスト向けの国際公募賞。9つの賞（賞金・画材・メンタリング・レジデンス機会を含む総額£5,000超）。1〜3点で応募可。", tags: ["新進作家向け", "メディア不問", "応募料あり"], what: "新進アーティストを対象にした国際公募賞。総額£5,000超・9賞（賞金、アーティスト用画材、メンタリング、レジデンス機会を含む）。作品は最大3点まで応募可。ショートリストは2026/8/10、受賞者は2026/8/17に発表、オンライン展示は8/11〜9/7。", why: "ジャンル横断の新進作家として国際的な評価軸に出せる。レジデンス機会を含む賞のため、今後の制作展開にもつながる。", fee: "締切は2026/8/3。応募料は公式サイト『Apply』ページで要確認。", url: "https://www.newemergenceart.com/apply" }
      ]
    },
    {
      label: "C. 海外｜レジデンス・サイトスペシフィック（受付中）",
      items: [
        { id: "wells-art-contemporary-2026", title: "Wells Art Contemporary 2026", org: "Wells Cathedral（英）｜海外・公募／サイトスペシフィック", deadline: "2026/06/30", cv: "mid", cvText: "中〜高。ウェルズ大聖堂での展示。サイトスペシフィック部門があり、祈り・支持体の主題と空間が強く接続。海外輸送・設営の負担は要考慮。", tags: ["サイトスペシフィック可", "メディア不問"], what: "ウェルズ大聖堂で100点超を展示。2部門：『Site-Specific Installations（内外への設置提案）』締切6/30・£30／『Gallery（2D・3D作品）』締切8/11・£20。1作家最大4点。展示2026/10/10〜11/7。", why: "祈り・不在・支持体の主題と大聖堂空間が強く接続。サイトスペシフィックなインスタ案をそのまま提案できる。", fee: "Site-specific £30／Gallery £20（26歳未満の美大生は£12）。", url: "https://www.wellsartcontemporary.co.uk/for-artists" },
        { id: "wassaic-project-2027", title: "Wassaic Project 2027 Artist Residencies", org: "Wassaic Project（米NY州）｜国際・レジデンス", deadline: "2026/07/01", cv: "mid", cvText: "中〜高。制度的な国際レジデンス歴になる。渡航費負担を考慮。", tags: ["分野不問", "国際可", "応募料 $25"], what: "夏季・冬季のオンサイト・レジデンス（単一公募で両季を受付）。版・紙・金属・素材系の制作環境。費用はスライド制$0〜$900。2027夏は6〜9月の各期。", why: "写真を支持体・素材・立体へ展開する制作を深める滞在。国際レジデンス歴は『プロジェクト実施力』を示す材料になる。", fee: "締切は2026/7/1。応募料$25（経済的事情で免除可）。渡航費は自己負担。", url: "https://wassaicproject.org/apply" },
        { id: "proyectoace-residency-2026", title: "Proyecto'ace Production and Exploration Residencies（第3回公募）", org: "Proyecto'ace（アルゼンチン・ブエノスアイレス）｜海外・レジデンス", deadline: "2026/07/31", cv: "mid", cvText: "中。応募無料の国際レジデンス。写真からドローイング・転写・版画的プロセスへの展開を、専門スタッフのサポート付きで試行できる。", tags: ["応募無料", "国際", "分野横断"], what: "視覚芸術・サウンド・パフォーマンス等幅広い分野のプロ/新進アーティスト対象の4週間レジデンス。年4回公募（締切1/31, 4/30, 7/31, 10/31）。スタジオ・設備・材料・滞在費の一部が提供される。", why: "写真を起点に転写・版画的プロセスへ展開する制作を、ブエノスアイレスで集中的に試せる。応募無料で参加しやすい。", fee: "締切は2026/7/31。応募無料。", url: "https://www.proyectoace.org/en/residencies/production-residencies/" },
        { id: "coca-project-2026-2027", title: "COCA PROJECT 2026-2027（第5回・国際公募）", org: "COCA PROJECT（伊・プーリア州）｜海外・レジデンス＋制作助成＋出版", deadline: "2026/09/20", cv: "mid", cvText: "中。プーリアの工芸文化と接続できる滞在制作＋資金提供＋出版がパッケージになった国際公募。", tags: ["国際", "制作助成つき", "出版掲載"], what: "イタリア・プーリア州Grottaglie（陶芸の街）またはTarantoでのレジデンス（1〜5月・10〜11月）。選出作品はCOCAが資金提供し、世界のどこでも実現可能。2026年版公式出版物に掲載。事前選考は無料。", why: "プーリアの陶芸・工芸的環境で、写真起点の金属・転写・mixed mediaのサイトスペシフィック新作を制作助成つきで展開できる。", fee: "締切は2026/9/20（または定員に達するまで）。事前選考は無料。", url: "https://cocaproject.art/2026-2027/" },
        { id: "pioneer-works-residency-2027", title: "Pioneer Works 2027 Visual Arts & Music Residency", org: "Pioneer Works（米NY・ブルックリン）｜国際・レジデンス", deadline: "2026/07/13", cv: "high", cvText: "高。応募無料で渡米実費以外の費用負担が小さい。5か月の滞在制作＋一括US$5,000の支援＋スタジオ・設備（リソグラフ・暗室・陶芸スタジオ・大判プリンタ・3Dプリンタ・レーザーカッター等）が無料提供される、制度的に手厚い国際レジデンス。", tags: ["応募無料", "国際", "5か月滞在"], what: "ブルックリンのPioneer Worksが毎年12名を選出するビジュアルアート・レジデンス（5か月間）。一括US$5,000の支援（オナラリウムUS$2,500＋月額US$500のスタイペンド）、無料スタジオ、リソグラフ・暗室・陶芸スタジオ・大判プリンタ・3Dプリンタ・レーザーカッター等の設備、キュレーター・批評家との隔週スタジオビジット、パブリックプログラムへの無料アクセスが提供される。2027年版の応募受付は2026/6/15〜7/13。", why: "金属・転写・立体・mixed mediaの実制作環境（暗室・陶芸スタジオ・大判プリンタ等）が無料で揃う、応募無料の国際レジデンス。渡航費以外の負担が小さい。", fee: "締切は2026/7/13 23:59 EST。応募無料。", url: "https://pioneerworks.org/residency/visual-arts" },
        { id: "arteventura-residency-2027", title: "Arteventura Artist Residency – Open Call 2027", org: "arteventura（スペイン・アンダルシア／シエラ・デ・アラセナ）｜海外・レジデンス（ローリング受付）", deadline: "随時受付中", cv: "mid", cvText: "中。固定締切がないローリング受付で出しやすく、4〜12週間の滞在制作枠を選べる。スタジオ・滞在設備が充実。", tags: ["ローリング受付", "応募料€20", "4週間〜"], what: "アンダルシア・シエラ・デ・アラセナの25ヘクタールの森に位置する、オフグリッドの国際レジデンス。2027年の滞在期間は2027/2/1〜12/14、4週間または6週間単位（最短4週間〜最長12週間まで延長可）。300㎡の共同スタジオと個別アパートを提供。定員35名、応募は受信順に処理。", why: "金属・転写・mixed mediaの実制作を、都市から離れた環境で集中的に試せる。固定締切がなく、スケジュールを合わせて出しやすい。", fee: "ローリング受付（固定締切なし、定員35名のため早期応募推奨）。応募料€20。", url: "https://arteventura.eu/artists-in-residence/open-call" }
      ]
    }
  ],
  upcoming: [
    { id: "mimoca-eye-vol2", title: "第2回 MIMOCA EYE", org: "丸亀市猪熊弦一郎現代美術館｜国内・美術館個展機会", opens: "2026/07/15", deadline: "2026/09/15", cv: "high", tags: ["36歳以下", "活動歴概ね3年以上", "ジャンル不問"], what: "現代美術館での個展機会が付く公募。ジャンル不問。応募資格は『2026/4/1時点で36歳以下・活動歴概ね3年以上・美術館での個展未経験』。応募は無料（制作・出品費は自己負担）。", url: "https://www.mimoca.jp/mimoca-eye/vol2/" },
    { id: "asahi-art-grant-2027", title: "朝日新聞文化財団 芸術活動助成（美術・2027年度）", org: "朝日新聞文化財団｜国内・助成", opens: "2026/07/01", deadline: "2026/10/25", cv: "mid", tags: ["展覧会・プロジェクト助成"], what: "2027年度(2027/4〜2028/3実施)の美術分野の活動への助成。受付は2026/7/1〜10/25。今後の個展・プロジェクトの資金計画に組み込める。", url: "https://www.asahizaidan.or.jp/grant/grant01.html" },
    { id: "tokas-emerging-2027", title: "TOKAS-Emerging 2027", org: "トーキョーアーツアンドスペース（東京都歴史文化財団）｜国内・個展支援プログラム", opens: "2026/06/26", deadline: "2026/07/31", cv: "high", tags: ["35歳以下", "日本在住（地方可）", "個展開催支援"], what: "1991/4/1以降生まれ（35歳以下）・日本在住の若手アーティスト対象。TOKAS本郷での個展開催機会（2027年4〜5月）を4名に提供。会場無償提供、制作支援金15万円、輸送費補助、設営補助、広報協力等。二次審査面接は2026/9/18。", url: "https://www.tokyoartsandspace.jp/archive/application/2026/20260616-331.html" },
    { id: "face-2027", title: "FACE 2027", org: "SOMPO美術財団／SOMPO美術館｜国内・公募展（平面）", opens: "2026/09/07", deadline: "2026/10/08", cv: "mid", tags: ["年齢・所属不問", "平面のみ", "写真・ミクストメディア可"], what: "第15回。年齢・所属不問の全国公募・現代絵画コンテスト。油彩・アクリル・水彩・版画・染織・写真・ミクストメディア等の平面作品が対象（立体・映像・共同制作不可）。グランプリ・優秀賞・U30フロンティア賞。展覧会は2027/3/6〜28、SOMPO美術館。", url: "https://www.sompo-museum.org/news/2026/face2027/" }
  ],
  openings: [
    { id: "takaishii-kyoto-anastassiades-2026", gallery: "タカ・イシイギャラリー 京都", area: "京都", title: "マイケル・アナスタシアデス「From Warm Yellow to Saturated Red」", artist: "Michael Anastassiades", when: "レセプション 2026/6/6（土）15:30–17:30", date: "2026/06/06", note: "会期 2026/6/6–7/4（京都）", url: "https://www.takaishiigallery.com/jp/", tags: ["レセプション時間あり"] },
    { id: "shugoarts-toya-2026", gallery: "ShugoArts（シュウゴアーツ）", area: "東京・六本木", title: "戸谷成雄追悼展「彫刻家・戸谷成雄」", artist: "戸谷成雄", when: "オープン 2026/6/6（土）", date: "2026/06/06", address: "東京都港区六本木6-5-24 complex665 2F", note: "会期 2026/6/6–6/27（六本木）", url: "https://shugoarts.com/", tags: [] },
    { id: "kosakukanechika-aoki-2026", gallery: "KOSAKU KANECHIKA", area: "東京・京橋", title: "青木豊「節とつぶて」", artist: "青木豊", when: "オープン 2026/6/12（金）", date: "2026/06/12", note: "会期 2026/6/12–7/25（京橋）", url: "https://kosakukanechika.com/", tags: [] },
    { id: "takaishii-roppongi-gokita-2026", gallery: "タカ・イシイギャラリー 六本木", area: "東京・六本木", title: "五木田智央「Lush Life」", artist: "五木田智央", when: "レセプション 2026/6/27（土）17:00–19:00", date: "2026/06/27", note: "会期 2026/6/27–7/25（六本木・京橋）", url: "https://www.takaishiigallery.com/jp/", tags: ["レセプション時間あり"] }
  ],
  onview: [
    { id: "onview-koyama-kyobashi-ahn", gallery: "小山登美夫ギャラリー京橋", area: "東京・京橋", title: "アン・ジサン「昼、夜」", artist: "アン・ジサン", dates: "2026/4/25–6/6", ends: "2026/06/06", url: "https://www.tokyoartbeat.com/events/-/Ahn-Jisan-Day-Night/tomio-koyama-gallery-kyobashi/2026-04-25", tags: ["#絵画・平面"] },
    { id: "onview-foam-matsuoka", gallery: "FOAM CONTEMPORARY", area: "東京・銀座", title: "Yohta Matsuoka「Life on the Table」", artist: "松岡陽太", dates: "2026/5/23–6/10", ends: "2026/06/10", url: "https://www.tokyoartbeat.com/events/-/Yohta-Matsuoka-Life-on-the-Table/foam-contemporary/2026-05-23", tags: ["#絵画・平面"] },
    { id: "onview-koyama-roppongi-neto", gallery: "小山登美夫ギャラリー六本木", area: "東京・六本木", title: "エルネスト・ネト「Dreaming Beings」", artist: "Ernesto Neto", dates: "2026/5/2–6/13", ends: "2026/06/13", url: "https://www.tokyoartbeat.com/events/-/Ernesto-Neto-Dreaming-Beings/53785-C88/2026-05-02", tags: ["#彫刻・立体"] },
    { id: "onview-takaishii-okuyama", gallery: "タカ・イシイギャラリー フォトグラフィー/フィルム", area: "東京・六本木", title: "奥山由之「photographs」", artist: "奥山由之", dates: "2026/5/15–6/13", ends: "2026/06/13", url: "https://www.tokyoartbeat.com/events/-/Yoshiyuki-Okuyama-Photographs/1-A21-DB-85/2026-05-15", tags: ["#写真"] },
    { id: "onview-voidplus-koromo", gallery: "void+（ヴォイドプラス）", area: "東京・青山", title: "衣真一郎「石室」", artist: "衣真一郎", dates: "2026/5/16–6/13", ends: "2026/06/13", url: "https://www.tokyoartbeat.com/events/-/Shinichiro-Koromo-Stone-Chamber/15-E4-AC-9-F/2026-05-16", tags: ["#絵画・平面"] },
    { id: "onview-maki-ando", gallery: "Maki Fine Arts", area: "東京・神楽坂", title: "安藤由莉「Rendering」", artist: "安藤由莉", dates: "2026/5/16–6/14", ends: "2026/06/14", url: "https://www.tokyoartbeat.com/events/-/Yuri-Ando-Rendering/975-EFF-82/2026-05-16", tags: ["#絵画・平面"] },
    { id: "onview-takaishii-yamashita", gallery: "タカ・イシイギャラリー京橋", area: "東京・京橋", title: "山下紘加「白気 White Veils」", artist: "山下紘加", dates: "2026/5/16–6/20", ends: "2026/06/20", url: "https://www.tokyoartbeat.com/events/-/Hiroka-Yamashita-White-Veils/taka-ishii-gallery-kyobashi/2026-05-16", tags: ["#絵画・平面"] },
    { id: "onview-standingpine-leeufan", gallery: "STANDING PINE 東京", area: "東京・天王洲", title: "李禹煥 + クロード・ヴィアラ + ジャンフランコ・ザッペティーニ 展", artist: "李禹煥 ほか", dates: "2026/5/23–6/20", ends: "2026/06/20", url: "https://www.tokyoartbeat.com/events/-/Lee-Ufan-Claude-Viallat-Gianfranco-Zappettini-Exhibition/standing-pine-tokyo/2026-05-23", tags: ["#絵画・平面"] },
    { id: "onview-spaceun-roy", gallery: "space Un", area: "東京・青山", title: "アンリ・ロア「DEVOTION」", artist: "Henry Roy", dates: "2026/4/25–6/21", ends: "2026/06/21", url: "https://www.tokyoartbeat.com/events/-/Henry-Roy-Devotion/space-un/2026-04-25", tags: ["#写真"] },
    { id: "onview-igallery-nordstroem", gallery: "i GALLERY", area: "大阪", title: "C.R. ノルドストローム/東京ビルド「Iteration（反復）」", artist: "Christopher Robin Nordström", dates: "2026/5/23–6/22", ends: "2026/06/22", url: "https://www.tokyoartbeat.com/events/-/Christopher-Robin-Nordstroem-Tokyo-Build-Iteration/i-gallery/2026-05-23", tags: ["関西", "#彫刻・立体"] },
    { id: "onview-kayokoyuki-suwa", gallery: "KAYOKOYUKI", area: "東京・六本木", title: "諏訪未知「PANTALOON」", artist: "諏訪未知", dates: "2026/5/23–6/27", ends: "2026/06/27", url: "https://www.tokyoartbeat.com/events/-/Michi-Suwa-Pantaloon/E0-E4379-E/2026-05-23", tags: ["#絵画・平面"] },
    { id: "onview-kennakahashi-landscape", gallery: "KEN NAKAHASHI", area: "東京・新宿", title: "「In a Landscape」", artist: "グループ展", dates: "2026/4/10–6/27", ends: "2026/06/27", url: "https://www.tokyoartbeat.com/events/-/In-a-Landscape/C1768938/2026-04-10", tags: ["#絵画・平面"] },
    { id: "onview-poeticscape-endo", gallery: "POETIC SCAPE", area: "東京・中目黒", title: "遠藤文香「Kanoko」", artist: "遠藤文香", dates: "2026/5/16–6/28", ends: "2026/06/28", url: "https://www.tokyoartbeat.com/events/-/Ayaka-Endo-Kanoko/5-C2060-D7/2026-05-16", tags: ["#写真"] },
    { id: "onview-koyanagi-marclay", gallery: "ギャラリー小柳", area: "東京・銀座", title: "クリスチャン・マークレー「LISTENING」", artist: "Christian Marclay", dates: "2026/4/4–6/30", ends: "2026/06/30", url: "https://www.tokyoartbeat.com/events/-/Christian-Marclay-Listening/5693-F25-A/2026-04-04", tags: ["#絵画・平面"] },
    { id: "onview-snow-fuse", gallery: "SNOW Contemporary", area: "東京・六本木", title: "布施琳太郎「タイムトラベラーのための展覧会」", artist: "布施琳太郎", dates: "2026/5/22–7/4", ends: "2026/07/04", url: "https://www.tokyoartbeat.com/events/-/Rintaro-Fuse-Exhibition-for-Time-Travelers/B203-D9-DE/2026-05-22", tags: ["#映像・映画"] },
    { id: "onview-fergus-fischer", gallery: "ファーガス・マカフリー 東京", area: "東京・青山", title: "ウルス・フィッシャー「間違い探し」", artist: "Urs Fischer", dates: "2026/4/11–7/5", ends: "2026/07/05", url: "https://www.tokyoartbeat.com/events/-/Urs-Fischer-Machigai-Sagashi-Spot-the-Difference/E622-CDFE/2026-04-11", tags: ["#インスタレーション"] },
    { id: "onview-gyre-spectrum", gallery: "GYRE GALLERY", area: "東京・表参道", title: "「SPECTRUM 2076 AD ── 来たる世界の意識体」", artist: "グループ展", dates: "2026/5/22–7/12", ends: "2026/07/12", url: "https://www.tokyoartbeat.com/events/-/Spectrum-2076-AD-Conscious-Entities-of-the-Coming-World/886471-D5/2026-05-22", tags: [] },
    { id: "onview-kikutake-nerhol", gallery: "Yutaka Kikutake Gallery", area: "東京・六本木", title: "Nerhol「Unseen Body」", artist: "Nerhol", dates: "2026/5/23–7/18", ends: "2026/07/18", url: "https://www.tokyoartbeat.com/events/-/Nerhol-Unseen-Body/11-B9-DD-0-F/2026-05-23", tags: [] },
    { id: "onview-suchsize-hayakawa-onishi", gallery: "SUCHSIZE（サッチサイズ）", area: "大阪", title: "早川祐太 + 大西伸明「drifting elements」", artist: "早川祐太 / 大西伸明", dates: "2026/4/17–6/13", ends: "2026/06/13", url: "https://www.tokyoartbeat.com/events/-/Yuta-Hayakawa-Nobuaki-Onishi-Drifting-Elements/suchsize/2026-04-17", tags: ["関西", "#彫刻・立体"] },
    { id: "onview-kouichi-ryczek", gallery: "KOUICHI FINE ARTS", area: "大阪", title: "マルチン・リチェク「ハーモニー」", artist: "Marcin Ryczek", dates: "2026/5/11–6/13", ends: "2026/06/13", url: "https://www.tokyoartbeat.com/events/-/Marcin-Ryczek-Harmony/kouichi-fine-arts/2026-05-11", tags: ["関西", "#写真"] },
    { id: "onview-plusy-kitatsuji", gallery: "+Y Gallery", area: "大阪", title: "北辻良央 展", artist: "北辻良央", dates: "2026/5/19–6/12", ends: "2026/06/12", url: "https://www.tokyoartbeat.com/events/-/Yoshihisa-Kitatsuji-Exhibition/y-gallery/2026-05-19", tags: ["関西", "#彫刻・立体"] },
    { id: "onview-parco-osaka-igarashi", gallery: "PARCO GALLERY OSAKA", area: "大阪", title: "「A–Z Homage to Takenobu Igarashi」", artist: "五十嵐威暢 ほか", dates: "2026/5/22–6/14", ends: "2026/06/14", url: "https://www.tokyoartbeat.com/events/-/A-Z-Homage-to-Takenobu-Igarashi/parco-gallery-osaka/2026-05-22", tags: ["関西"] },
    { id: "onview-tezukayama-resonance", gallery: "TEZUKAYAMA GALLERY", area: "大阪", title: "「律動のレゾナンス」", artist: "グループ展", dates: "2026/5/23–6/20", ends: "2026/06/20", url: "https://www.tokyoartbeat.com/events/-/Resonance-of-Rhythm/CEB-8-D156/2026-05-23", tags: ["関西", "#絵画・平面"] },
    { id: "onview-tezukayama-kato", gallery: "TEZUKAYAMA GALLERY", area: "大阪", title: "加藤智大「The face speaks」", artist: "加藤智大", dates: "2026/5/23–6/20", ends: "2026/06/20", url: "https://www.tokyoartbeat.com/events/-/Tomohiro-Kato-The-face-speaks/CEB-8-D156/2026-05-23", tags: ["関西", "#彫刻・立体"] },
    { id: "onview-artcourt-ishizuka", gallery: "ARTCOURT Gallery", area: "大阪", title: "石塚源太 作品集出版記念展「Relative Dimension」", artist: "石塚源太", dates: "2026/5/23–6/27", ends: "2026/06/27", url: "https://www.tokyoartbeat.com/events/-/Genta-Ishizuka-Relative-Dimension-Book-Launch-Exhibition/artcourt-gallery/2026-05-23", tags: ["関西", "#陶芸・漆"] },
    { id: "onview-isseymiyake-semba-nishimura", gallery: "ISSEY MIYAKE SEMBA | CREATION SPACE", area: "大阪", title: "西村陽一郎「光がふれる、折りとかたち」", artist: "西村陽一郎", dates: "2026/5/1–6/27", ends: "2026/06/27", url: "https://www.tokyoartbeat.com/events/-/Yoichiro-Nishimura-Touched-by-Light-Folds-and-Forms/issey-miyake-semba-creation-space/2026-05-01", tags: ["関西", "#インスタレーション"] },
    { id: "onview-hillgate-kusui", gallery: "ギャラリーヒルゲート", area: "京都", title: "楠井沙耶「かかる木」", artist: "楠井沙耶", dates: "2026/1/12–6/14", ends: "2026/06/14", url: "https://www.tokyoartbeat.com/events/-/Saya-Kusui-The-leaning-tree/gallery-hillgate/2026-01-12", tags: ["関西", "#彫刻・立体"] },
    { id: "onview-sokyo-narita", gallery: "SOKYO（祇園）", area: "京都", title: "成田輝「最小限の断片」", artist: "成田輝", dates: "2026/5/14–6/11", ends: "2026/06/11", url: "https://www.tokyoartbeat.com/events/-/Hikaru-Narita-Minimal-Fragments/sokyo/2026-05-14", tags: ["関西", "#彫刻・立体"] },
    { id: "onview-nonakahill-idetsu", gallery: "ノナカ・ヒル京都", area: "京都", title: "出津京子「酷暑」", artist: "出津京子", dates: "2026/5/16–7/11", ends: "2026/07/11", url: "https://www.tokyoartbeat.com/events/-/Kyoko-Idetsu-Extreme-Heat/nonaka-hill-kyoto/2026-05-16", tags: ["関西", "#絵画・平面"] },
    { id: "onview-leica-kyoto-freitas", gallery: "ライカギャラリー京都", area: "京都", title: "テレサ・フレイタス「Colour Matter(s)」", artist: "Teresa Freitas", dates: "2026/5/16–7/19", ends: "2026/07/19", url: "https://www.tokyoartbeat.com/events/-/Teresa-Freitas-Colour-Matter-s/leica-gallery-kyoto/2026-05-16", tags: ["関西", "#写真"] },
    { id: "onview-hosoo-gates", gallery: "HOSOO GALLERY", area: "京都", title: "シアスター・ゲイツ「Glorious Robe」", artist: "Theaster Gates", dates: "2026/4/11–8/30", ends: "2026/08/30", url: "https://www.tokyoartbeat.com/events/-/Theaster-Gates-Glorious-Robe/3-C499056/2026-04-11", tags: ["関西", "#インスタレーション"] },
    { id: "onview-galleryten-takiguchi", gallery: "ギャラリー点", area: "京都", title: "瀧口修造「『妖精の距離』と『スフィンクス』」", artist: "瀧口修造", dates: "2026/4/25–7/26", ends: "2026/07/26", url: "https://www.tokyoartbeat.com/events/-/Shuzo-Takiguchi-Distance-of-a-Fairy-and-Sphinx/gallery-ten/2026-04-25", tags: ["関西", "#絵画・平面"] },
    { id: "onview-alab-tsuchiya", gallery: "A-LAB", area: "兵庫・尼崎", title: "土屋咲瑛「→第4の壁」", artist: "土屋咲瑛", dates: "2026/5/2–6/28", ends: "2026/06/28", url: "https://www.tokyoartbeat.com/events/-/Sae-Tsuchiya-The-Fourth-Wall/DB-28-ED-8-B/2026-05-02", tags: ["関西", "地元", "#絵画・平面"] }
  ],
  top3: [
    { title: "Future Generation Art Prize 2027", note: "（6/28・無料・メディア不問の国際大本命）本日WebSearchで公式情報に変更なしを再確認。ジャンル横断の目標に直結し、締切が最も近く最優先。" },
    { title: "Wells Art Contemporary 2026", note: "（6/30・サイトスペシフィック部門）本日WebSearchで公式情報に変更なしを再確認。大聖堂空間に祈り・支持体の主題を直接展開できる、インスタ案を出せる希少な機会。" },
    { title: "Art Award IN THE CUBE 2027", note: "（7/10・大賞500万円）専用キューブ空間でサイトスペシフィックなインスタレーションを発表できる国内最大級の公募。入選約10点にも製作支援60万円。" }
  ],
  excluded: [
    "hosq Notations #2（アルメニア）… 締切2026/6/10で受付終了（250件超の応募を受領との現地報道あり）。",
    "遊工房アートスペース レジデンス … 体制変更により閉鎖（恒久終了）。",
    "岡本太郎現代芸術賞（TARO賞）… 公式に現在の募集・締切の記載がないため掲載せず（次回募集を監視）。",
    "KAF Young Prize 2026（締切3/31）／ACTアート大賞展（2/8）／アイスタイル財団 助成（1/31）／BBA Artist Prize（2025/12/8）… 受付終了。",
    "小笠原敏晶記念財団 助成 … 2026年度は募集前（調整中）。前年実績では7〜9月募集。",
    "Hiroshima MoCA FIVE 25/26／TOKAS-Emerging／Tokyo Contemporary Art Award … 前回受付終了。次回を監視（TCAAは活動歴10年以上が対象で現段階は対象外）。",
    "CAF賞（学生限定）／Circulation(s)（欧州在住限定）／STPLN(Culture Moves Europe対象国在住限定)／The Bennett Prize（女性限定）… 応募資格の対象外。",
    "Photography+ Emerging Talent Issue 2026（Photoworks・英国）… 締切2026/6/15 16:00 UTCで本日時点では受付終了。",
    "第27回 日本・フランス現代美術世界展 エスパス・プリヴェ部門（JIAS／欧州美術クラブ）… 出品料に依存した商業サロン形式の公募展のため見送り。",
    "アーツサポート関西 2026年度公募助成「未来アート寄金」… 募集期間2025/12/8〜2026/1/8で本日時点では受付終了（次回募集を監視）。",
    "SHIBUYA AWARDS 2026-27／学園前アートフェスタ／兵庫県展2026／神戸新世紀秋季展 … 受付開始日・募集要項が公式に確認できず掲載せず（要追跡）。",
    "SCARTS企画公募2027 … 2026年度（令和8年度実施分）は採択済み（審査終了）。2027年度分の募集開始日・締切は本日時点で公式発表がなく、関連助成事業のサイクルから12月頃と推測されるに過ぎないため掲載を見送り（次回再確認）。",
    "岡本太郎現代芸術賞（TARO賞）次回（第30回） … 第29回（応募期間2025/6/30〜8/31）は終了済みで、第30回の募集要項・開始日は本日時点で未発表のため掲載を見送り。",
    "小笠原敏晶記念財団 助成 … 2026年度上期（交流助成・渡航助成）は募集期間2026/4/24〜6/18で本日時点では受付終了。現代美術分野の調査・研究等助成・翻訳助成（例年7〜9月頃）は2026年度分の正式な募集開始日が未発表のため掲載を見送り。",
    "アーツサポート関西 2026年度公募助成「未来アート寄金」次回（2027年度） … 2026年度分（募集2025/12/8〜2026/1/8）は受付終了済み。次回開始日は本日時点で未発表のため掲載を見送り。",
    "兵庫県展2026（第63回） … 前回（2025県展・第62回）は募集期間2025/9/8〜10/1。2026年版の公式募集案内が本日時点で見つからないため掲載を見送り（例年8月頃告知の可能性、要追跡）。",
    "U25 Art Contest 2026 … 受付中である可能性は高いが、応募締切日について出典間で『2026/7/31』『2026/9/11』の記載が混在し（7/31は応募資格の年齢基準日との混同の疑い）、確定できないため掲載を見送り。",
    "Beautiful Bizarre Art Prize 2026 … 公式サイトで締切2026/7/17（LA時間）等は確認できたが、作風がダークアート・イマジナリーリアリズム・ポップサーリアリズム系のコミュニティを中心としており、林稔里の写真起点mixed media実践とは方向性が合わないため掲載を見送り。",
    "LensCulture Art Photography Awards 2026 … 締切2025/12/17で本日時点では受付終了済み（受賞者発表済み）。次サイクルの募集開始は未発表。",
    "城崎国際アートセンター（兵庫県豊岡市）AIR 2026年度 … 兵庫県内の有力なレジデンスだが、2026年度募集の締切は2025/6/27で受付終了済み。2027年度の募集開始日は本日時点で確認できず見送り（地元・兵庫のため次回告知を要追跡）。",
    "ART IN THE OFFICE 2026（マネックスグループ） … Webエントリー締切2026/3/11・書類提出締切2026/4/9で本日時点では受付終了済み。",
    "Loewe Foundation Craft Prize 2027（第11回） … 2026年版（第10回）は応募終了済みで、2027年版の募集開始日は本日時点で確認できず見送り。",
    "【2026/6/20〜22】WebFetchツールが環境側の障害でgoogle.com・example.com等の無関係なサイトを含む全URLに403 Forbiddenを返す状態が3日連続で続き、主催公式ページへの直接アクセスができなかったため、新規候補の検証を見送り既存掲載分の締切経過チェックのみ実施した（経過した締切はなし）。",
    "【2026/6/23】WebFetchの不調が4日連続で継続（google.com・example.comも403）。本日はWebSearchツールによる代替検証で締切間近の5件の現状を確認し、新規3件（Brillia Art Award Wall 2026・R.E. Award 2026・Arteventura Artist Residency 2027）を公式情報に基づき追加。WebFetchによる直接アクセスではない点に留意。"
  ],
  disclaimer: "本日（2026/6/23）もWebFetchツールが環境側の障害（4日連続でgoogle.com・example.com等を含む全URLに403）のため使用できず、主催公式ページへブラウザ的に直接アクセスすることはできませんでした。代わりにWebSearchツールで各主催の公式情報を検索結果として直接確認する方式を用い、締切が近い5件（Berlin Photo Awards 6/27、Future Generation Art Prize 2027 6/28、熊谷正寿文化財団助成・Arte Laguna Prize・Wells Art Contemporary 各6/30）の内容に変更がないことを確認し、新規3件（Brillia Art Award Wall 2026・R.E. Award 2026・Arteventura Artist Residency 2027）を追加しました。その他の既存項目は2026/6/19の公式確認内容を締切経過チェックのうえ引き継いでいます。応募前には必ず公式ページをご自身で直接ご確認ください。"
};
